[env:dfrobot_beetle_esp32c3]
platform = espressif32
board = dfrobot_beetle_esp32c3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_ldf_mode = deep
lib_deps =
    sensirion/Sensirion I2C SHT4x @ ^1.1.0
    adafruit/Adafruit SH110X @ ^2.1.10
    adafruit/Adafruit GFX Library @ ^1.11.9