M48
; DRILL file {KiCad 9.0.7} date 2026-02-11T09:15:24+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-11T09:15:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.850
%
G90
G05
T1
X215.11Y-101.9
X220.89Y-101.9
T2
X235.5Y-99.5
X235.5Y-102.5
M30
